name: Build
on: [push]
jobs:
  runs-on: windows-2022
  steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: 'true'
        lfs: 'true'
        fetch-depth: '1'
    - name: Configure CMake with tests
      run: cmake --preset clangcl